/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bilibili_bililive_batteria_NativeTest */

#ifndef _Included_com_bilibili_bililive_batteria_NativeTest
#define _Included_com_bilibili_bililive_batteria_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bilibili_bililive_batteria_NativeTest
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bilibili_bililive_batteria_NativeTest_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
